### ISSUE TITLE
Update info message in a child

### ISSUE THREAD

**Issue by mpagels** [mpagels/kindr.garten#10]
**As a user,
I want to update an info message for the child over a http route, to the backend, 
so that I can insert new or update infos that is important for the KITA or the parents**

## Description
I want to send an update for the message info for a child.
- e.g. via postman

## Acceptance criterias
- [ ] when accessing via PUT`/api/message/<id>` I send an updated message data via JSON to the backend, it will save on the backend
- [ ] the JSON needs very important the `child` id
- [ ] the JSON needs very important the `from` field `PARENT | KITA` to identify, which one send the message, for filtering later in the frontend
- [ ] if message not found, send back error

## Tasks
- [ ] create PUT route `api/message/<id>`, accept json, save it to the message repo
  - [ ] write test for the repo
  - [ ] write test for the http request
- [ ] create `service` methods that save children data to repo
  - [ ] write test for the service
## Size
Medium
