### ISSUE TITLE
Delete message from a child

### ISSUE THREAD

**Issue by mpagels** [mpagels/kindr.garten#11]
**As a user,
I want to delete an info message for the child over a http route, to the backend, 
so that I can delete not necessary infos that is not important anymore or was incorrect for the KITA or the parents**

## Description
I want to delete a message info for a child.
- e.g. via postman

## Acceptance criterias
- [ ] when accessing via DELETE `/api/message/<id>` 
- [ ] delete the message
- [ ] if message not found, send back error

## Tasks
- [ ] create DELETE route `api/message/<id>`
- [ ] write Delete logic
  - [ ] write test for the repo
  - [ ] write test for the http request
- [ ] create `service` methods that delete message
  - [ ] write test for the service
## Size
Medium
