### ISSUE TITLE
Get child data from backend via postman

### ISSUE THREAD

**Issue by mpagels** [mpagels/kindr.garten#2]
**As a user,
I want to receive all children over a http route, that are saved in the backend, 
so that I have all the children data**

## Description
I want to get all children data from the backend
- e.g. via postman

## Acceptance criterias
- [ ] when accessing via GET `/api/child` I get an array with all available children data in the group
- [ ] when accessing via GET `api/child/<id>` I get an object with just the child data with that <id>

## Tasks
- [ ] create `child` java class with corresponding fields
  - [ ]  id string
  - [ ]  birthday date
  - [ ]  firstName string
  - [ ]  lastName string
  - [ ]  email string
  - [ ]  password string
  - [ ]  profilImage string
- [ ] create `repo` that holds all children objects
  - [ ] write test for the repo
- [ ] create `service` that holds business logic for the children repo
  - [ ] write test for the service
- [ ] create GET route `api/child` to get all children in an array
  - [ ] write test for the http request
- [ ] create GET route  `api/child/<id>` to get just an object with the child with the corresponding <id>
  - [ ] write test for the http request

## Size
Medium
