### ISSUE TITLE
Post new child data

### ISSUE THREAD

**Issue by mpagels** [mpagels/kindr.garten#3]
**As a user,
I want to post new child data over a http route, to the backend, 
so that I can save a ne child to the group**

## Description
I want to send data to and create a new child on the backend
- e.g. via postman

## Acceptance criterias
- [ ] when accessing via POST`/api/child` I send child data via JSON to the backend, it will save on the backend

## Tasks
- [ ] create POST route `api/child`, accept json, save it to the repo
  - [ ] write test for the repo
  - [ ] write test for the http request
- [ ] create `service` methods that save children data to repo
  - [ ] write test for the service
## Size
Small
