### ISSUE TITLE
Update child data on backend via http route

### ISSUE THREAD

**Issue by mpagels** [mpagels/kindr.garten#4]
**As a user,
I want to update child data over a http route, on the backend, 
so that I can edit child data in the group**

## Description
I want to update a child information on the backend
- e.g. via postman

## Acceptance criterias
- [ ] when accessing via PUT `api/child/<id>` I send the update information via JSON, it will be updated

## Tasks
- [ ] create PUT route `api/child/<id>`, accept json, save it to the repo
  - [ ] write test for the repo
  - [ ] write test for the http request
- [ ] create `service` methods that update children data to repo
  - [ ] write test for the service

## Size
Medium
