### ISSUE TITLE
Delete child

### ISSUE THREAD

**Issue by mpagels** [mpagels/kindr.garten#5]
**As a user,
I want to delete a child data over a http route, on the backend, 
so that the child data is no longer part of the group**

## Description
I want to delete child information on the backend
- e.g. via postman

## Acceptance criterias
- [ ] when accessing via DELETE `api/child/<id>` I the child will be deleted

## Tasks
- [ ] create DELETE route `api/child/<id>`, deletes child from repo
  - [ ] send back error, if child is not found
  - [ ] write test for the repo
  - [ ] write test for the http request
- [ ] create `service` methods that deletes child data from repo
  - [ ] write test for the service

## Size
Medium
