### ISSUE TITLE
Update a child contact 

### ISSUE THREAD

**Issue by mpagels** [mpagels/kindr.garten#7]
**As a user,
I want to update a contact from a child over a http route, to the backend, 
so that If something changes, the contact is updated**

## Description
The parents need to be able to edit contacts, so that will be visible to the frontend
- e.g. via postman

## Acceptance criterias
- [ ] when accessing via PUT `/api/child/<id>/contact/<contactID>` I send updated contact data via JSON to the backend, it will update the contact data to the child (<id> contact (<contactID) on the backend

## Tasks
- [ ] create PUT route `api/child/<id>/contact/<contactID>`, accept json, update the contact in the child in the repo
  - [ ] write test for the repo
  - [ ] write test for the http request
- [ ] create `service` methods that save the contact data in the children repo
  - [ ] write test for the service
## Size
Small
