### ISSUE TITLE
Delete child contact

### ISSUE THREAD

**Issue by mpagels** [mpagels/kindr.garten#8]
**As a user,
I want to delete a contact from a child over a http route, to the backend, 
so that If I don't need it anymore, the contact is deleted**

## Description
The parents need to be able to delete contacts, so that will not be available anymore
- e.g. via postman

## Acceptance criterias
- [ ] when accessing via DELETE `/api/child/<id>/contact/<contactID>` the contact will be delete
- [ ]  if contact was not found, send error back

## Tasks
- [ ] create DELETE route `api/child/<id>/contact/<contactID>`,
- [ ] Delete contact from child
  - [ ] write test for the repo
  - [ ] write test for the http request
- [ ] create `service` methods that delete the contact data in the children repo
  - [ ] write test for the service
## Size
Small
