### ISSUE TITLE
Post and create a message for a child

### ISSUE THREAD

**Issue by mpagels** [mpagels/kindr.garten#9]
**As a user,
I want to post a new info message for the child over a http route, to the backend, 
so that I can save a new info that is important for the KITA or the parents**

## Description
I want to send a message info for a child. That message could be comming from the parents, for the KITA or from the KITA for the parents
- e.g. via postman

## Acceptance criterias
- [ ] when accessing via POST`/api/message` I send a message data via JSON to the backend, it will save on the backend
- [ ] the JSON needs very important the `child` id
- [ ] the JSON needs very important the `from` field `PARENT | KITA` to identify, which one send the message, for filtering later in the frontend

## Tasks
- [ ] create POST route `api/message`, accept json, save it to the message repo
  - [ ] id string
  - [ ] child_ID string
  - [ ] message string
  - [ ] from string
  - [ ] created_at timestamp
  - [ ] write test for the repo
  - [ ] write test for the http request
- [ ] create `service` methods that save children data to repo
  - [ ] write test for the service
## Size
Medium
